apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-secret
data:
  POSTGRES_USER: "bWljcm9zZXJ2aWNlcw==" # "microservices"
  POSTGRES_PASSWORD: "bWljcm9zZXJ2aWNlcw==" # "microservices"